#!/bin/bash
# This script loops over all the -cool.ptx files in a folder
# and creates the pdfs in the output folder

outFolder=../../output/cools

# Loop over all the pdf files in the folder
for f in *-cool.ptx
do
  # Remove the .ptx extension from the file name
  base=${f%.ptx}

  # message
  echo "found $base.ptx"
  xsltproc ~/.ptx/xsl/pretext-latex-cool.xsl $base.ptx > $outFolder/$base.tex
done