#!/bin/bash
# This script loops over all the -cool.ptx files in a folder
# and creates the tex files in the output folder
# it also copies all the images that are used in the .tex files so that they compile

# Need to create this folder
outFolder=../../output/cools
ASSETSDIRECTORY=../../source/assets

mkdir $outFolder
mkdir $outFolder/jpg-source
mkdir $outFolder/png-source
mkdir $outFolder/svg-source
mkdir $outFolder/tikz-source

# Loop over all the -cool.ptx files in the folder
for f in *-cool.ptx
do
  # Remove the .ptx extension from the file name
  base=${f%.ptx}

  # message
  echo "found $base.ptx"

  # generate the .tex file for the -cool.ptx file
  # custom xsl file custom-xsl/pretext-latex-cool.xsl needs to be placed in 
  # the pretext xsl folder (it depends on the other pretext xsl files)
  xsltproc ~/.ptx/xsl/pretext-latex-cool.xsl $base.ptx > $outFolder/$base-standalone.tex
done

# Search for 'includegraphics' in .tex files and extract the file path
find $outFolder -name "*.tex" -exec grep -H "includegraphics\[" {} \; | sed -n -e 's/.*\\includegraphics.*{\(.*\)}.*/\1/p' | \
xargs -I {} cp "$ASSETSDIRECTORY/{}" "$outFolder/{}"



for texfile in "$outFolder"/*.tex; do
  pdflatex -output-directory="$outFolder" "$texfile" 
done