#!/bin/bash
# This script loops over all the pdf files in a folder
# and executes a command for the ones that don't have a corresponding svg version

# Loop over all the pdf files in the folder
for f in *.pdf
do
  # Remove the .pdf extension from the file name
  base=${f%.pdf}

  # Check if there is a svg file with the same name
  if [ ! -f $base.svg ]
  then
    # Execute the command for the pdf file
    # Uses pdf2svg. To install use [brew install pdf2svg]
    # Uses rsvg. To install use [brew install librsvg]
    pdf2svg $f $base.svg
    rsvg-convert --zoom 1.25 --format svg --output $base.svg $base.svg
    
    # message
    echo "Created $base.svg using [pdf2svg and scaled it up with svg-convert]"    
  fi
done