#!/bin/bash
# This script loops over all the -cool.ptx files in a folder and
#  *  creates the tex files in the specified output folder $outFolder using the custom pretext-latex-cool.xsl
#  *  copies all the images that are used in the .tex files so that they compile
#  *  compiles the files into pdf using pdflatex


# folders (relative to folder of a unit)
outFolder=../assets/cools-pdf
ASSETSDIRECTORY=../../source/assets

# create the necessary output folders
# mkdir $outFolder
# mkdir $outFolder/jpg-source
# mkdir $outFolder/png-source
# mkdir $outFolder/svg-source
# mkdir $outFolder/tikz-source

# Loop over all the -cool.ptx files in the folder
for f in *-cool.ptx
do
  # Remove the .ptx extension from the file name
  base=${f%.ptx}

  # message
  echo "found $base.ptx"

  # generate the .tex file for the -cool.ptx file
  # custom xsl file custom-xsl/pretext-latex-cool.xsl needs to be placed in 
  # the pretext xsl folder (it depends on the other pretext xsl files)
  xsltproc ~/.ptx/xsl/pretext-latex-cool.xsl $base.ptx > $outFolder/$base-standalone.tex
  # run pdflatex on the file and place in the outfolder
  # two passes due to the fancy image header
  pdflatex -output-directory="$outFolder" $outFolder/$base-standalone.tex
  pdflatex -output-directory="$outFolder" $outFolder/$base-standalone.tex
done

# Search for 'includegraphics' in .tex files, 
# extract the file path, and 
# move the images from the assets folder to the output folder
# find $outFolder -name "*.tex" -exec grep -H "includegraphics\[" {} \; | sed -n -e 's/.*\\includegraphics.*{\(.*\)}.*/\1/p' | \
# xargs -I {} cp "$ASSETSDIRECTORY/{}" "$outFolder/{}"


# Build the tex files at the outFolder
# for texfile in "$outFolder"/*.tex; do
  # pdflatex -output-directory="$outFolder" "$texfile"
# done